### ISSUE TITLE
Кэширование изображений(image proxy)

### ISSUE THREAD

**Issue by yuszafar** [yuszafar/blog-CRUD-eldor#5]

**Comment by electrofocus** [comment]
В чём суть задания?

**Comment by yuszafar** [comment]
закешировать изображение. Те если пользователь два раза делает запрос на 1 и тоже изображение с одним с одним и тем же размером, то изображения надо доставать из кеша. Если таск сложный можете оставить на последок.

**Comment by yuszafar** [comment]
Для кеширование используется redis(временная БД). Также есть аналоговые БД, например RabbitMQ
